/**
 * Core domain types for RepoPulse Lite.
 *
 * These types model the data flowing through the analysis pipeline
 * as described in SPEC.md section 4:
 *
 *   GitHub API → Telemetry → Normalizer → Heuristic Engine → Score + Report
 */

// ---------------------------------------------------------------------------
// GitHub API raw shapes
// ---------------------------------------------------------------------------

/** Subset of the GitHub repository object used by the analysis pipeline. */
export interface GitHubRepository {
  id: number;
  full_name: string;
  description: string | null;
  stargazers_count: number;
  forks_count: number;
  open_issues_count: number;
  default_branch: string;
  pushed_at: string;
  created_at: string;
  updated_at: string;
  archived: boolean;
}

/** Subset of a GitHub commit list item. */
export interface GitHubCommitListItem {
  sha: string;
  commit: {
    author: {
      name: string;
      email: string;
      date: string;
    };
    message: string;
  };
}

/** Subset of the GitHub commit detail (includes file stats). */
export interface GitHubCommitDetail {
  sha: string;
  commit: {
    author: {
      name: string;
      email: string;
      date: string;
    };
    message: string;
  };
  stats: {
    additions: number;
    deletions: number;
    total: number;
  };
  files: Array<{
    filename: string;
    additions: number;
    deletions: number;
    changes: number;
    status: string;
  }>;
}

// ---------------------------------------------------------------------------
// Normalized telemetry model
// ---------------------------------------------------------------------------

/** A single commit in the normalized internal representation. */
export interface NormalizedCommit {
  sha: string;
  authorName: string;
  authorEmail: string;
  date: Date;
  message: string;
  additions: number;
  deletions: number;
  totalChanges: number;
  filesChanged: number;
}

/** The full normalized telemetry object passed into the scoring engine. */
export interface RepositoryTelemetry {
  repository: {
    fullName: string;
    description: string | null;
    stars: number;
    forks: number;
    openIssues: number;
    defaultBranch: string;
    pushedAt: Date;
    createdAt: Date;
    updatedAt: Date;
    archived: boolean;
  };
  commits: NormalizedCommit[];
}

// ---------------------------------------------------------------------------
// Scoring engine output
// ---------------------------------------------------------------------------

/** Individual dimension score with its weight and raw value. */
export interface DimensionScore {
  /** Human-readable dimension name. */
  name: string;
  /** Normalized score for this dimension (0–100). */
  score: number;
  /** Weight applied when computing the composite health score. */
  weight: number;
}

/** All dimension scores produced by the heuristic engine. */
export interface HealthDimensions {
  codeChurn: DimensionScore;
  commitHygiene: DimensionScore;
  commitCadence: DimensionScore;
  authorEntropy: DimensionScore;
  anomalyDetection: DimensionScore;
}

/** Full output of the heuristic scoring engine. */
export interface ScoringResult {
  /** Composite 0–100 health score. */
  healthScore: number;
  dimensions: HealthDimensions;
}

// ---------------------------------------------------------------------------
// API contract
// ---------------------------------------------------------------------------

/** Request body for POST /api/analyze. */
export interface AnalyzeRequest {
  /** Public GitHub repository URL (e.g. https://github.com/owner/repo). */
  repoUrl: string;
}

/** Successful response from POST /api/analyze. */
export interface AnalysisResult {
  repoFullName: string;
  scoring: ScoringResult;
  /** Executive risk report generated by the LLM. */
  report: string;
  /** ISO 8601 timestamp of when the analysis was performed. */
  analyzedAt: string;
}

/** Error response from POST /api/analyze. */
export interface AnalysisError {
  error: string;
  /** Optional machine-readable error code. */
  code?: string;
}
